### ISSUE TITLE
Plans for MVC 5?

### ISSUE THREAD

**Issue by futureturnip** [gravplats/crowbar#3]
Great project! 

I tried to use it in an MVC 5 application, and receive an error page with a 500 error with the message "This operation requires IIS integrated pipeline mode."

The project I'm "testing" is the default MVC 5 template. The route I'm trying to test is the "/Home/Contact" route.

Do you have any ideas.

Thanks so much for this project.

**Comment by mrydengren** [comment]
I haven't had the time to address MVC 5 yet, but I quickly added an ASP.NET MVC 5 test project (upgraded from ASP.NET MVC 4) to Crowbar (https://github.com/mrydengren/crowbar/tree/mvc5).

I have a few failing tests involving forms authentication and anti-forgery request token, but I've believe the same happened when I upgraded from MVC 3 to 4 as well (no time to address these issue either). But nothing resembling the issue you experienced.

I don't have the default MVC 5 template at the moment (is it in VS2013? - I haven't upgraded yet).

They might have included something that isn't currently supported by the [CrowbarHttpWorker](https://github.com/mrydengren/crowbar/blob/master/src/Crowbar/CrowbarHttpWorker.cs).

Could you push your project as an example?

**Comment by futureturnip** [comment]
Thanks for your help. Yes, the template is in VS2013. I just simply create the out-of-the-box MVC project "WebApplication1" (with Unit Tests). The test I currently have attempts to get /Home/Index and asserts that the result is html and ok.

Here's the repo: https://github.com/futureturnip/CrowbarMvc5Starter

Any insight you may have is helpful.

**Comment by mrydengren** [comment]
Ok, it's seems to be the OWIN host that makes the test fail. Once I remove everything OWIN-related from the project it works. Unfortunately, I have no time to research how to get things working with OWIN.

A a couple of tips when writing tests though. Be sure to only create the proxy once, ie. `private static readonly MvcApplication.Create("MvcProject");` in a base class. Otherwise your tests will be very slow since it's time-consuming to create the proxy. Also you should to use the `ShouldHaveStatusCode` extension method.

``` C#
  var response = client.Get("/");
  response.ShouldBeHtml();
  response.ShouldHaveStatusCode(HttpStatusCode.OK);
```

It will produce a much more descriptive error message (at least with NUnit and the ReSharper test runner).

```
Crowbar.CrowbarException : An exception was thrown during the execution of the test.
  ----> Crowbar.AssertException : HTTP status code should have been 'OK' but was 'InternalServerError'.

Raw HTTP request:

GET http://localhost/
Content-Type: application/octet-stream

Raw HTTP response:

HTTP/1.0 500 Internal Server Error
X-AspNet-Version: 4.0.30319
Cache-Control: private
Content-Type: text/html; charset=utf-8
Content-Length: 4851

<!DOCTYPE html>
<html>
    <head>
        <title>This operation requires IIS integrated pipeline mode.</title>
        <meta name="viewport" content="width=device-width" />
        <style>
         body {font-family:"Verdana";font-weight:normal;font-size: .7em;color:black;} 
         p {font-family:"Verdana";font-weight:normal;color:black;margin-top: -5px}
         b {font-family:"Verdana";font-weight:bold;color:black;margin-top: -5px}
         H1 { font-family:"Verdana";font-weight:normal;font-size:18pt;color:red }
         H2 { font-family:"Verdana";font-weight:normal;font-size:14pt;color:maroon }
         pre {font-family:"Consolas","Lucida Console",Monospace;font-size:11pt;margin:0;padding:0.5em;line-height:14pt}
         .marker {font-weight: bold; color: black;text-decoration: none;}
         .version {color: gray;}
         .error {margin-bottom: 10px;}
         .expandable { text-decoration:underline; font-weight:bold; color:navy; cursor:hand; }
         @media screen and (max-width: 639px) {
          pre { width: 440px; overflow: auto; white-space: pre-wrap; word-wrap: break-word; }
         }
         @media screen and (max-width: 479px) {
          pre { width: 280px; }
         }
        </style>
    </head>

    <body bgcolor="white">

            <span><H1>Server Error in '/' Application.<hr width=100% size=1 color=silver></H1>

            <h2> <i>This operation requires IIS integrated pipeline mode.</i> </h2></span>

            <font face="Arial, Helvetica, Geneva, SunSans-Regular, sans-serif ">

            <b> Description: </b>An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code.

            <br><br>

            <b> Exception Details: </b>System.PlatformNotSupportedException: This operation requires IIS integrated pipeline mode.<br><br>

            <b>Source Error:</b> <br><br>

            <table width=100% bgcolor="#ffffcc">
               <tr>
                  <td>
                      <code>

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.</code>

                  </td>
               </tr>
            </table>

            <br>

            <b>Stack Trace:</b> <br><br>

            <table width=100% bgcolor="#ffffcc">
               <tr>
                  <td>
                      <code><pre>

[PlatformNotSupportedException: This operation requires IIS integrated pipeline mode.]
   System.Web.HttpResponse.get_Headers() +214
   Microsoft.Owin.Host.SystemWeb.CallHeaders.AspNetResponseHeaders..ctor(HttpResponseBase response) +37
   Microsoft.Owin.Host.SystemWeb.OwinCallContext.CreateEnvironment() +492
   Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.IntegratedPipelineContext.GetInitialEnvironment(HttpApplication application) +263
   Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.IntegratedPipelineContext.PrepareInitialContext(HttpApplication application) +19
   Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.IntegratedPipelineContextStage.BeginEvent(Object sender, EventArgs e, AsyncCallback cb, Object extradata) +462
   System.Web.AsyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +556
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean&amp; completedSynchronously) +288
</pre></code>

                  </td>
               </tr>
            </table>

            <br>

            <hr width=100% size=1 color=silver>

            <b>Version Information:</b>&nbsp;Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.0.30319.18055

            </font>

    </body>
</html>
<!-- 
[PlatformNotSupportedException]: This operation requires IIS integrated pipeline mode.
   at System.Web.HttpResponse.get_Headers()
   at Microsoft.Owin.Host.SystemWeb.CallHeaders.AspNetResponseHeaders..ctor(HttpResponseBase response)
   at Microsoft.Owin.Host.SystemWeb.OwinCallContext.CreateEnvironment()
   at Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.IntegratedPipelineContext.GetInitialEnvironment(HttpApplication application)
   at Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.IntegratedPipelineContext.PrepareInitialContext(HttpApplication application)
   at Microsoft.Owin.Host.SystemWeb.IntegratedPipeline.IntegratedPipelineContextStage.BeginEvent(Object sender, EventArgs e, AsyncCallback cb, Object extradata)
   at System.Web.HttpApplication.AsyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
-->


   at Crowbar.ClientResponseAssertExtensions.ShouldHaveStatusCode(ClientResponse response, HttpStatusCode expectedStatusCode)
   at WebApplication1.Tests.Controllers.HomeControllerTest.<CrowbarTheIndex>b__0(Client client)
   at Crowbar.MvcApplicationProxy`1.ProcessCore(SerializableDelegate`1 script, THttpApplication application, String testBaseDirectory, IHttpPayloadDefaults defaults)
--AssertException
   at Crowbar.ClientResponseAssertExtensions.ShouldHaveStatusCode(ClientResponse response, HttpStatusCode expectedStatusCode)
   at WebApplication1.Tests.Controllers.HomeControllerTest.<CrowbarTheIndex>b__0(Client client)
   at Crowbar.MvcApplicationProxy`1.ProcessCore(SerializableDelegate`1 script, THttpApplication application, String testBaseDirectory, IHttpPayloadDefaults defaults)
```

**Comment by futureturnip** [comment]
Thank you.
